name: workflow dispatch
on:
  push:
    branches:
      - add-workflow-dispatch
  workflow_dispatch: {}

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: "echo Hello"