name: Deploy Application

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  call-deployment-workflow:
    uses: Syota622/github_action_common/.github/workflows/deploy.yml@main
    with:
      environment: 'production'
