name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  call-deployment-workflow:
    uses: Syota622/github_action_common/.github/workflows/deploy.yml@main
    with:
      environment: 'production'
    secrets:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
