name: Deploy Application

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
    # opened: プルリクエストが作成されたとき
    # synchronize: プルリクエストが更新されたとき
    types: [opened, synchronize]

permissions:
  contents: read
  id-token: write

jobs:
  call-deployment-workflow:
    uses: Syota622/github_action_common/.github/workflows/deploy.yml@main
    with:
      ENV_VAR: >-
        ${{ 
          github.ref == 'refs/heads/main' && 'prod' || 
          github.event_name == 'pull_request' && 'stg' || 
          github.ref == 'refs/heads/develop' && 'dev' 
        }}
    secrets:
      # SLACK_WEBHOOK_URL_STG: ${{ secrets.SLACK_WEBHOOK_URL_STG }}
      SLACK_WEBHOOK_URL_FAILED: ${{ secrets.SLACK_WEBHOOK_URL_FAILED }}
      SLACK_WEBHOOK_URL_FAILED_2: ${{ secrets.SLACK_WEBHOOK_URL_FAILED_2 }}
      # わざと失敗させるステップを追加
      - name: Force Failure
        run: exit 1