name: Workflow Error Monitor

on:
  workflow_run:
    workflows: ['Deploy Application']  # 監視対象のワークフロー名
    types: [requested, action_required, completed]

jobs:
  notify-workflow-error:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Workflow Error
        uses: rtCamp/action-slack-notify@v2.3.2
        if: github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.status == 'failure'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_FAILED }}
          SLACK_TITLE: GitHub Actions 失敗通知
          SLACK_COLOR: danger
          SLACK_MESSAGE: |
            <!here> GitHub Actionsワークフローでエラーが発生しました
            エラータイプ: ${{ github.event.workflow_run.conclusion == null && 'Syntax Error' || 'Execution Error' }}
            ワークフロー: ${{ github.event.workflow_run.name }}
            ステータス: ${{ github.event.workflow_run.status }}
            結果: ${{ github.event.workflow_run.conclusion }}
            リポジトリ: ${{ github.repository }}
            参照URL: ${{ github.event.workflow_run.html_url }}

      - name: Debug Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow status: ${{ github.event.workflow_run.status }}"
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"