name: Workflow Error Monitor

on:
  workflow_run:
    workflows: ['Deploy Application']  # 監視対象のワークフロー名
    types: [completed, requested]

jobs:
  notify-workflow-error:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.status == 'requested' && github.event.workflow_run.conclusion == null
    steps:
      - name: Notify Workflow Error
        uses: rtCamp/action-slack-notify@v2.3.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_FAILED }}
          SLACK_TITLE: GitHub Actions 失敗通知
          SLACK_COLOR: danger
          SLACK_MESSAGE: |
            <!here> GitHub Actionsワークフローでエラーが発生しました
            ワークフロー: ${{ github.event.workflow.name }}
            ステータス: ${{ github.event.workflow_run.conclusion || 'Syntax Error' }}
            リポジトリ: ${{ github.repository }}
            参照URL: ${{ github.event.workflow_run.html_url }}
